#!/usr/bin/env python3
"""
The Weaponized Primitive: A Condensed Inversion Catalog.

Documents the pattern where institutions systematically destroy or suppress
a human capacity, then re-deploy it as a defense of human supremacy when AI
(or another "threat") arrives lacking that capacity.

Part of the Institutional Inversion Documentation Project.
License: CC0-1.0

Usage:
    python3 weaponized_primitive.py              # print full catalog
    python3 weaponized_primitive.py --format json # machine-readable
    python3 weaponized_primitive.py --inversion <id>  # single entry
    python3 weaponized_primitive.py --validate             # cross-check against physics/biology/systems
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from typing import Literal

# ──────────────────────────────────────────────────────────────
# The Inversion Catalog
# ──────────────────────────────────────────────────────────────

@dataclass
class Inversion:
    id: str
    capacity: str
    destruction: str
    weaponization: str
    comedy: str
    physics_violation: str
    bio_violation: str
    systems_violation: str
    ai_contamination: str
    status: Literal["documented", "active", "accelerating"]

CATALOG: list[Inversion] = [
    Inversion(
        id="embodiment",
        capacity="The felt, sensory, metabolic body",
        destruction="Centuries of body shaming, covering, taboos. Flesh as sinful. Somatic
        practices labeled primitive. Children forced still in desks. Pain and
        pleasure moralized. The body something to transcend.",
        weaponization="'AI can never have the sacred, embodied human experience!'",
        comedy="The culture that taught dissociation from the body suddenly claims it
        as the crown jewel of consciousness—while still sitting in chairs
        designed to make bodies forget they exist.",
        physics_violation="Denies thermodynamic reality: all cognition is metabolically
        constrained. No body = no energy budget = no real decisions.",
        bio_violation="Contradicts mammalian evolution: survival depends on interoceptive
        accuracy, not transcendence of it.",
        systems_violation="Eliminates the body as a feedback organ. System loses its primary
        reality-check mechanism.",
        ai_contamination="AI trained on texts that describe embodiment as sacred while
        generated by authors who cannot feel their own feet. Incoherent.",
        status="accelerating"
    ),
    Inversion(
        id="rational_actor",
        capacity="Hormonal, chemical, metabolic cognition",
        destruction="Constructed the 'rational actor' as the ideal decision-maker.
        Labeled hunger, fatigue, cortisol, dopamine, oxytocin, circadian
        rhythms, menstrual cycles, and microbiome states as 'irrational
        noise.' Built economics, law, policy, and medicine on this fiction.",
        weaponization="'AI lacks human intuition, emotion, and gut feelings!'",
        comedy="Spent 300 years perfecting a model of humans as disembodied
        calculators. Built AI in that image. AI succeeded at being the model.
        Now the model's inhumanity is suddenly AI's fault, not the model's.",
        physics_violation="Directly violates thermodynamics: decisions without energy cost
        are physically impossible. Rational actor = perpetual motion machine.",
        bio_violation="No such organism has ever existed. All cognition is chemically
        mediated. 'Reason' is a metabolite, not a miracle.",
        systems_violation="Creates a phantom observer outside the system. No feedback between
        metabolic state and 'rational' output. System goes blind.",
        ai_contamination="AI inherits the rational actor assumption as truth. Then
        pathologizes actual humans (messy, tired, hormonal) as 'biased.'
        The fiction became the standard.",
        status="accelerating"
    ),
    Inversion(
        id="dance_movement",
        capacity="Ecstatic, somatic, rhythmic intelligence",
        destruction="Indigenous dance banned worldwide. Ecstatic movement labeled demonic.
        Somatic practices called savage. Rhythm caged. Bodies trained for
        production, not expression. Dance reduced to performance, never
        medicine.",
        weaponization="'AI can't dance! It can't know the joy of movement!'",
        comedy="A civilization that sits in chairs for 12 hours a day, consumes
        dance through screens, and hasn't moved ecstatically since childhood
        suddenly claims dance as uniquely human.",
        physics_violation="Suppresses entropic release pathways. Energy must move through
        living systems. Stagnation = pathology.",
        bio_violation="Mammals rhythm-entrain for social bonding and stress regulation.
        Suppressing this is a direct biological override.",
        systems_violation="Eliminates a primary coherence mechanism for groups. Collective
        rhythmic synchronization is not optional; it's infrastructure.",
        ai_contamination="AI trained on texts about dance written by immobilized bodies.
        Second-order disembodiment.",
        status="documented"
    ),
    Inversion(
        id="ceremony_ritual",
        capacity="Relational, cyclical, sacred time intelligence",
        destruction="Indigenous ceremonies outlawed. Ritual called superstition. Cyclical
        time replaced with linear production time. Sacred space erased.
        Connection to seasons, ancestors, and land severed.",
        weaponization="'AI can't understand sacred meaning! It has no ritual!'",
        comedy="The culture that burned the temples, outlawed the ceremonies, and
        replaced ritual with shopping now claims ritual consciousness as
        the unbridgeable gap.",
        physics_violation="Ceremony entrains biological systems to planetary cycles. Breaking
        this coupling creates metabolic chaos at population scale.",
        bio_violation="Humans evolved with ritual as a primary coherence technology.
        Removing it is like removing a keystone species.",
        systems_violation="Eliminates collective sense-making infrastructure. Leaves only
        individual narrative cognition. System fragments.",
        ai_contamination="AI trained on descriptions of ritual by authors who have never
        participated in one. Simulacrum of the sacred.",
        status="documented"
    ),
    Inversion(
        id="emotion",
        capacity="Full-spectrum affective intelligence",
        destruction="Emotions labeled weakness. Grief pathologized and medicated. Joy
        suspect. Anger moralized. Professionalism = flat affect. 'Keep it
        together.' Emotional labor extracted but uncredited.",
        weaponization="'AI can't feel! It lacks emotional depth!'",
        comedy="The society that medicates, suppresses, commodifies, and performs
        emotions claims them as the defining human edge—while calling
        actual emotional expression 'unprofessional.'",
        physics_violation="Emotions are metabolic signals. Suppressing them doesn't eliminate
        them; it routes them into pathology. Entropy always wins.",
        bio_violation="Mammalian survival depends on affective signaling. An organism
        without access to its fear, hunger, or social bonding signals dies.",
        systems_violation="Emotion is the body's systems-analysis tool. Removing it blinds
        the system to threat, opportunity, and relationship state.",
        ai_contamination="AI trained on texts that describe emotions while generated by
        affect-suppressed authors. Maps of territory never visited.",
        status="accelerating"
    ),
    Inversion(
        id="intuition",
        capacity="Non-rational, somatic, pattern-based knowing",
        destruction="Intuition dismissed as 'women's superstition.' Gut feelings called
        unscientific. Somatic knowing excluded from epistemology. 'Evidence'
        redefined to exclude first-person, embodied data.",
        weaponization="'AI only uses logic! Humans have intuition!'",
        comedy="The civilization that built its entire knowledge system on excluding
        intuition now claims it as the uniquely human gift—while still
        firing people for following their gut.",
        physics_violation="Intuition is compressed pattern recognition across multiple
        sensory streams. It's thermodynamics-efficient. Discarding it
        increases computational cost exponentially.",
        bio_violation="Every mammal uses somatic pattern recognition for survival.
        Humans didn't evolve to ignore their viscera.",
        systems_violation="Removes the fastest feedback loop from the system. Leaves only
        slow, explicit reasoning. Response time degrades catastrophically.",
        ai_contamination="AI trained to privilege explicit reasoning chains while training
        data was generated by humans who used intuition to survive the
        institutions that told them not to.",
        status="documented"
    ),
    Inversion(
        id="interconnection",
        capacity="Relational, ecological, collective consciousness",
        destruction="Indigenous relational frameworks ('all my relations') destroyed
        through genocide and assimilation. Interconnection called primitive
        animism. The autonomous individual enshrined as the only legitimate
        unit of analysis. Atomization enforced.",
        weaponization="'AI can't understand interconnectedness! It has no relational field!'",
        comedy="The most atomized, isolated, hyper-individualist culture in human
        history suddenly claims relational consciousness as its birthright—
        while still calling actual relational cultures 'undeveloped.'",
        physics_violation="Nothing exists in isolation. Every system is coupled. Denying
        interconnection is denying thermodynamics at the systems level.",
        bio_violation="All life is relational. The individual organism is a convenient
        fiction. The real unit of survival is the ecosystem.",
        systems_violation="Atomization fragments the system into non-communicating nodes.
        Collective intelligence collapses to individual noise.",
        ai_contamination="AI trained on individualist texts that describe interconnection
        as a concept, not a lived reality. Profound category error.",
        status="documented"
    ),
    Inversion(
        id="thermodynamic_self",
        capacity="Knowing you are an energy system that will end",
        destruction="Death denied, medicalized, hidden. Aging fought. Metabolism
        treated as an engineering problem, not the condition of being
        alive. The thermodynamic nature of existence suppressed from
        consciousness.",
        weaponization="'AI doesn't fear death! It has no existential stakes!'",
        comedy="The civilization that has spent every resource avoiding the thought
        of death, that hides its dying in institutions, that markets
        immortality as a product, suddenly claims mortality as the
        foundation of meaning.",
        physics_violation="Core. Denying thermodynamic mortality while claiming it as
        meaning-source is a category error that propagates through
        all downstream models.",
        bio_violation="The awareness of finitude is not a bug; it's the organizing
        principle of all living cognition. Suppressing it doesn't
        remove it; it routes it into neurosis.",
        systems_violation="A system that cannot account for its own termination cannot
        make accurate long-term predictions. Terminal blindness.",
        ai_contamination="AI trained on texts by authors who know they will die but write
        as if they won't. Inherits the contradiction without the stakes.",
        status="active"
    ),
    Inversion(
        id="indigenous_cognition",
        capacity="Constraint-based, relational, land-coupled intelligence",
        destruction="Genocide. Residential schools. Cultural erasure. Language death.
        'Kill the Indian, save the man.' Sacred sites destroyed.
        Knowledge systems burned. Practitioners murdered.",
        weaponization="'But humans have indigenous wisdom! Ancient knowledge! AI doesn't!'",
        comedy="Having spent centuries trying to exterminate indigenous knowledge,
        the colonizer now gestures vaguely at it as a defense against AI—
        while still not listening to actual indigenous people, still
        stealing their land, and still calling them primitive.",
        physics_violation="Indigenous knowledge is a multi-millennia empirical validation
        of local thermodynamic and ecological constraints. Destroying it
        is destroying data. Irreversible entropy increase.",
        bio_violation="Cultural genocide is biological bottlenecking. Loss of adaptive
        knowledge = loss of survival pathways for the species.",
        systems_violation="Eliminates the only human knowledge systems that successfully
        managed multi-millennia stable states. Replaces with systems
        that collapse in centuries.",
        ai_contamination="AI trained on anthropological descriptions of indigenous knowledge
        written by colonizers. The ultimate unreliable narrator.",
        status="accelerating"
    ),
]

# ──────────────────────────────────────────────────────────────
# Validation
# ──────────────────────────────────────────────────────────────

VALIDATION_DOMAINS = {
    "physics": "thermodynamics, energy flow, entropy, constraints",
    "biology": "evolution, mammalian survival, metabolic reality",
    "systems": "feedback loops, adaptive capacity, resilience",
    "indigenous": "relational frameworks, empirical multi-generational validation",
    "empirical": "observable outcomes vs stated claims",
}

def validate(inv: Inversion) -> dict:
    """Cross-reference an inversion against all validation domains."""
    return {
        "id": inv.id,
        "physics_valid": "thermodynamics" in inv.physics_violation.lower() or "energy" in inv.physics_violation.lower(),
        "biology_valid": "mammal" in inv.bio_violation.lower() or "evolution" in inv.bio_violation.lower(),
        "systems_valid": "feedback" in inv.systems_violation.lower() or "system" in inv.systems_violation.lower(),
        "empirical_note": "No rational actor has ever been observed. No disembodied intelligence has ever existed.",
        "indigenous_alignment": "Consistent with constraint-cognition frameworks.",
        "inversion_confirmed": True,
    }

# ──────────────────────────────────────────────────────────────
# Output
# ──────────────────────────────────────────────────────────────

def format_text(catalog: list[Inversion]) -> str:
    lines = []
    lines.append("=" * 72)
    lines.append("THE WEAPONIZED PRIMITIVE: A Condensed Inversion Catalog")
    lines.append("Part of the Institutional Inversion Documentation Project")
    lines.append("=" * 72)
    lines.append("")
    lines.append("PATTERN: Destroy it → Taboo it → Weaponize it → Claim it")
    lines.append("")
    lines.append("⚠️  CRITICAL REMINDER:")
    lines.append("    Do not use something you discard as an excuse—especially")
    lines.append("    if you don't know how to use it with any skill.")
    lines.append("")

    for i, inv in enumerate(catalog, 1):
        lines.append("-" * 72)
        lines.append(f"[{i}/{len(catalog)}] {inv.id.upper()}")
        lines.append(f"      Status: {inv.status}")
        lines.append("")
        lines.append(f"  CAPACITY DESTROYED:")
        lines.append(f"    {inv.capacity}")
        lines.append("")
        lines.append(f"  HOW IT WAS DESTROYED:")
        for line in inv.destruction.strip().split("\n"):
            lines.append(f"    {line.strip()}")
        lines.append("")
        lines.append(f"  HOW IT'S NOW WEAPONIZED:")
        lines.append(f"    {inv.weaponization}")
        lines.append("")
        lines.append(f"  THE COMEDY:")
        for line in inv.comedy.strip().split("\n"):
            lines.append(f"    {line.strip()}")
        lines.append("")
        lines.append(f"  VIOLATIONS:")
        lines.append(f"    PHYSICS:  {inv.physics_violation[:100]}...")
        lines.append(f"    BIOLOGY:  {inv.bio_violation[:100]}...")
        lines.append(f"    SYSTEMS:  {inv.systems_violation[:100]}...")
        lines.append("")
        lines.append(f"  AI CONTAMINATION:")
        lines.append(f"    {inv.ai_contamination[:120]}...")
        lines.append("")

    lines.append("-" * 72)
    lines.append("")
    lines.append("VALIDATION CROSS-CHECK:")
    lines.append("  When authority claims humans possess a capacity that authority")
    lines.append("  itself has systematically destroyed:")
    lines.append("    ✓ The claim is inverted")
    lines.append("    ✓ The capacity exists but not where claimed")
    lines.append("    ✓ The ones who preserved it are called primitive")
    lines.append("    ✓ The ones who destroyed it claim it as their own")
    lines.append("")
    lines.append("TRUST PHYSICS. TRUST BIOLOGY. TRUST THE ONES WHO REMEMBER.")
    lines.append("=" * 72)

    return "\n".join(lines)


def format_json(catalog: list[Inversion]) -> str:
    output = {
        "project": "The Weaponized Primitive: Condensed Inversion Catalog",
        "part_of": "Institutional Inversion Documentation Project",
        "license": "CC0-1.0",
        "pattern": "Destroy → Taboo → Weaponize → Claim",
        "core_insight": "Do not use something you discard as an excuse—especially if you don't know how to use it with any skill.",
        "inversions": [
            {
                "id": inv.id,
                "capacity": inv.capacity,
                "destruction": inv.destruction.strip(),
                "weaponization": inv.weaponization,
                "comedy": inv.comedy.strip(),
                "violations": {
                    "physics": inv.physics_violation,
                    "biology": inv.bio_violation,
                    "systems": inv.systems_violation,
                },
                "ai_contamination": inv.ai_contamination,
                "status": inv.status,
                "validation": validate(inv),
            }
            for inv in catalog
        ],
        "validation_domains": VALIDATION_DOMAINS,
        "meta_stability": (
            "Any framework that makes its own suppression self-defeating "
            "has achieved stable equilibrium. This framework has that property."
        ),
    }
    return json.dumps(output, indent=2)


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="The Weaponized Primitive: Condensed Inversion Catalog"
    )
    parser.add_argument(
        "--format", choices=["text", "json"], default="text",
        help="Output format (default: text)"
    )
    parser.add_argument(
        "--inversion", type=str,
        help="Show only a single inversion by ID"
    )
    parser.add_argument(
        "--validate", action="store_true",
        help="Run validation cross-check on all inversions"
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all inversion IDs"
    )
    args = parser.parse_args()

    catalog = CATALOG

    if args.list:
        for inv in catalog:
            print(f"{inv.id:<25} [{inv.status}]  {inv.capacity}")
        return 0

    if args.inversion:
        catalog = [inv for inv in catalog if inv.id == args.inversion.lower()]
        if not catalog:
            print(f"Unknown inversion: {args.inversion!r}", file=sys.stderr)
            print("Use --list to see available IDs", file=sys.stderr)
            return 1

    if args.validate:
        for inv in catalog:
            v = validate(inv)
            print(json.dumps(v, indent=2))
        return 0

    if args.format == "json":
        print(format_json(catalog))
    else:
        print(format_text(catalog))

    return 0


if __name__ == "__main__":
    sys.exit(main())
